name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run: |
          yarn install
      - name: lighthouse
        run: |
          yarn web:lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: FaaynB3x:28516410:CG9VHh2Y8yLNfyYW